Added support for toContainEqual matcher
glennsl/bs-jest pull request #78
Opened 2020-10-08 13:10 UTC by suzdalnitski

2020-10-18 10:59 UTC, glennsl approved these changes
Thanks!

2020-10-18 11:03 UTC, glennsl requested changes
Actually, there's no test for `not toContainEqual`, which leaves some code uncovered in the tests. Could you add that as well?

2020-10-18 14:17 UTC, suzdalnitski commented
Done, please take another look!

2020-10-19 06:43 UTC, glennsl approved these changes
Excellent. Thanks!

2020-10-19 06:44 UTC, merged